# Generated by Django 3.2.5 on 2021-07-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
