# Generated by Django 3.2.5 on 2021-07-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student'),
        ('events', '0006_event_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='students.student'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_of_event',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(),
        ),
    ]
