# Generated by Django 3.2.5 on 2021-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210711_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_of_event',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
