# Generated by Django 3.2.5 on 2021-07-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210711_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
