# Generated by Django 3.2.5 on 2021-07-11 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('date_of_event', models.DateField()),
                ('start_of_event', models.TimeField(blank=True, null=True)),
                ('end_of_event', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='students.student')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
