# Generated by Django 3.2.5 on 2021-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_of_event',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_of_event',
            field=models.TimeField(null=True),
        ),
    ]
