# Generated by Django 3.2.5 on 2021-07-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210711_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
