# Generated by Django 3.2.5 on 2021-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('primanry_contact', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
