# Generated by Django 3.2.5 on 2021-07-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_memo'),
        ('students', '0003_student_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='events.event'),
        ),
    ]
