# Generated by Django 3.2.5 on 2021-07-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
