# Generated by Django 3.2.5 on 2021-07-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_primary_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='primary_contact',
        ),
    ]
